import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const gruposData = [
  {
    nome: "Por Profissão",
    slug: "profissao",
    ordem: 1,
    categorias: [
      "Dev / Programador",
      "Data Scientist / Analytics",
      "DevOps / SysAdmin",
      "Cybersecurity",
      "QA / Tester",
      "Designer Gráfico",
      "UI/UX Designer",
      "Motion Designer",
      "Fotógrafo",
      "Editor de Vídeo",
      "Ilustrador / Artista Digital",
      "Arquiteto / 3D",
      "Animador",
      "Streamer",
      "YouTuber",
      "Podcaster",
      "Social Media Manager",
      "Copywriter / Redator",
      "Influencer",
      "Trader / Day Trader",
      "Empreendedor / Startup",
      "Consultor",
      "Contador",
      "Analista Financeiro",
      "Engenheiro (CAD/Projetos)",
      "Cientista / Pesquisador",
      "Produtor Musical",
      "Sound Designer",
      "Editor de Áudio",
      "Professor / Educador",
      "Estudante Universitário",
      "Vestibulando / Concurseiro",
      "Médico / Profissional de Saúde",
      "Advogado",
      "Gamer Casual",
      "Pro Player / E-sports",
      "Game Dev",
      "Speedrunner",
      "Colecionador / Retro Gamer",
      "Escritor / Autor",
      "Tradutor",
      "Virtual Assistant",
      "Atendimento / Suporte",
      "Freelancer Generalista",
    ],
  },
  {
    nome: "Por Configuração",
    slug: "configuracao",
    ordem: 2,
    categorias: [
      "Single Monitor",
      "Dual Monitor",
      "Dual Monitor (Horizontal)",
      "Dual Monitor (Vertical + Horizontal)",
      "Triple Monitor",
      "Quad Monitor",
      "Monitor + Tablet/iPad",
      "Ultrawide (21:9)",
      "Super Ultrawide (32:9)",
      "Monitor Curvo",
      "Monitor Vertical (Portrait)",
      "Monitor Stacked (empilhado)",
      "TV como Monitor",
      "Mesa Reta / Tradicional",
      "Mesa em L",
      "Mesa em U",
      "Standing Desk / Mesa Elevatória",
      "Mesa Suspensa / Floating Desk",
      "Mesa de Canto",
      "Mesa com Painel Pegboard",
      "Bancada / Countertop",
      "Mesa DIY / Personalizada",
      "Tampo IKEA (Karlby, etc.)",
      "Laptop Setup",
      "Laptop + Monitor Externo",
      "Desktop Tower",
      "Mini PC / Mac Mini",
      "All-in-One (iMac, etc.)",
      "Workstation",
      "Monitor no Braço Articulado",
      "Monitor na Base Original",
      "Monitor na Parede (Wall Mount)",
      "Suporte para Laptop",
      "Setup 100% Suspenso",
      "Setup Simétrico",
      "Setup Assimétrico",
      "Setup de Canto",
      "Closet Office",
      "Setup em Nicho",
      "Setup Embaixo de Escada",
      "Setup na Varanda",
      "Setup Compartilhado (casal)",
      "Battlestation + Console",
      "Setup Híbrido (trabalho + gaming)",
      "Setup Portátil / Mobile",
      "Setup Dobrável",
      "Setup Multi-uso",
      "Setup de Frente pra Parede",
      "Setup de Frente pra Janela",
      "Setup no Meio do Ambiente",
      "Setup com Vista",
      "Com Deskpad / Mousepad Full",
      "Com Dock Station",
      "Com Hub USB",
      "Com Wireless Charging",
      "Com Iluminação Embutida",
    ],
  },
  {
    nome: "Por Estética",
    slug: "estetica",
    ordem: 3,
    categorias: [
      "Minimalista",
      "Moderno",
      "Industrial",
      "Nórdico / Escandinavo",
      "Japandi",
      "Mid-Century Modern",
      "Rústico",
      "Contemporâneo",
      "Art Deco",
      "Bauhaus",
      "Cyberpunk",
      "Synthwave / Retrowave",
      "Vaporwave",
      "Futurista / Sci-Fi",
      "Retrô / Vintage",
      "Steampunk",
      "Arcade / Fliperama",
      "Pixel Art / 8-bit",
      "Anime / Otaku",
      "K-Pop / Korean Style",
      "Cozy / Aconchegante",
      "Clean / Limpo",
      "Caótico Organizado",
      "Dark & Moody",
      "Bright & Airy",
      "Zen / Calmo",
      "Produtivo / Focado",
      "Inspirador",
      "Aesthetic",
      "ASMR-worthy",
      "RGB Full",
      "RGB Sutil",
      "Warm Light (Luz Quente)",
      "Cool Light (Luz Fria)",
      "Neon",
      "Backlit (Luz de Fundo)",
      "Natural Light (Luz Natural)",
      "Luz de LED Strip",
      "Nanoleaf / Painéis de LED",
      "Sem RGB (Anti-RGB)",
      "Monocromático",
      "All White / Whiteout",
      "All Black / Blackout",
      "Preto e Branco (P&B)",
      "Tons Terrosos / Earth Tones",
      "Pastel",
      "Tons Neutros",
      "Colorido / Vibrante",
      "Rosa / Pink Setup",
      "Verde / Green Setup",
      "Azul / Blue Setup",
      "Roxo / Purple Setup",
      "Vermelho / Red Setup",
      "Laranja / Orange Setup",
      "Amarelo / Yellow Setup",
      "Teal / Turquesa",
      "Amadeirado / Madeira Natural",
      "Amadeirado Escuro (Walnut)",
      "Amadeirado Claro (Oak/Maple)",
      "Metálico / Alumínio",
      "Concreto / Cimento Queimado",
      "Mármore",
      "Vidro",
      "Couro",
      "Tecido / Fabric",
      "Bambu",
      "Fosco / Matte",
      "Brilhante / Glossy",
      "Acetinado",
      "Texturizado",
      "Apple-inspired",
      "IKEA Style",
      "Setup Gringo",
      "Setup Brasileiro",
      "Pinterest-worthy",
      "Instagram-worthy",
      "Estilo Asiático",
      "Setup de Filme / Cinema",
      "Estilo Loft",
      "Estilo Apartamento",
      "Simétrico / Perfeito",
      "Assimétrico Intencional",
      "Maximalista",
      "Essencialista",
      "Cluttercore",
      "Coffee Shop Vibe",
      "Studio Vibe",
      "Biblioteca / Library",
      "Galeria de Arte",
      "Quarto de Hotel",
      "Cabana / Cottage",
      "Loft Urbano",
      "Tropical",
      "Desert / Deserto",
      "Natureza / Biophilic",
    ],
  },
  {
    nome: "Por Ambiente",
    slug: "ambiente",
    ordem: 4,
    categorias: [
      "Home Office",
      "Escritório no Quarto",
      "Quarto",
      "Sala de Estar",
      "Cozinha",
      "Varanda / Sacada",
      "Garagem",
      "Porão / Basement",
      "Sótão",
      "Closet Office",
      "Lavanderia",
      "Apartamento Pequeno",
      "Apartamento Grande",
      "Kitnet / Studio",
      "Casa",
      "Cobertura / Penthouse",
      "Loft",
      "República / Moradia Estudantil",
      "Quarto Alugado",
      "Cantinho (espaço mínimo)",
      "Nicho / Vão",
      "Embaixo de Escada",
      "Embaixo de Mezanino",
      "Integrado ao Ambiente",
      "Cômodo Dedicado",
      "Espaço Compartilhado",
      "Escritório Corporativo",
      "Coworking",
      "Startup Office",
      "Agência Criativa",
      "Estúdio de Gravação",
      "Estúdio de Fotografia",
      "Estúdio de Podcast",
      "Sala de Reunião",
      "Consultório",
      "Laboratório",
      "Setup de Canto",
      "Setup de Parede",
      "Setup no Centro do Ambiente",
      "Setup com Vista pra Janela",
      "Setup de Frente pra Parede",
      "Setup em Ilha",
      "Setup Embaixo de Janela",
      "Setup Solo",
      "Setup de Casal (side by side)",
      "Setup de Casal (frente a frente)",
      "Setup Família / Kids",
      "Setup Compartilhado (revezamento)",
      "Setup Pai e Filho",
      "Primeiro Setup",
      "Setup de Transição",
      "Setup Temporário",
      "Setup Definitivo",
      "Setup Tropical (clima quente)",
      "Setup pra Frio",
      "Com Janela Grande",
      "Sem Janela",
      "Pé Direito Alto",
      "Pé Direito Duplo",
      "Teto Inclinado",
      "Parede de Tijolo Aparente",
      "Parede de Concreto",
      "Com Espelho",
      "Com Prateleiras",
      "Com Pegboard",
      "Muita Luz Natural",
      "Pouca Luz Natural",
      "Sem Luz Natural",
      "Setup em RV / Motorhome",
      "Setup em Barco",
      "Setup de Viagem / Nômade Digital",
      "Setup de Hotel",
      "Setup de Airbnb",
      "Setup Outdoor",
      "Setup no Café / Cafeteria",
      "Com Vista pra Cidade",
      "Com Vista pra Natureza",
      "Com Vista pra Mar / Praia",
      "Com Vista pra Montanha",
      "Sem Vista (parede)",
      "Com Vista pra Jardim",
    ],
  },
  {
    nome: "Por Elementos",
    slug: "elementos",
    ordem: 5,
    categorias: [
      "Com Plantas",
      "Plantas Grandes / Statement Plant",
      "Plantas Pequenas / Suculentas",
      "Plantas Pendentes",
      "Plantas Artificiais",
      "Terrário",
      "Aquário",
      "Jardim Vertical",
      "Musgo Preservado",
      "Flores",
      "LED Strip",
      "Nanoleaf / Painéis de LED",
      "Ring Light",
      "Light Bar (monitor)",
      "Luminária de Mesa",
      "Luminária de Piso",
      "Neon Sign",
      "Luz de Fundo (atrás do monitor)",
      "Abajur",
      "Fita LED no setup",
      "Lâmpada Smart / RGB",
      "Luz de Vela / Simulação",
      "Quadros / Posters",
      "Neon Sign Personalizado",
      "Relógio de Parede",
      "Espelho",
      "Shelf Decor (prateleira decorativa)",
      "Discos de Vinil na Parede",
      "Tapeçaria / Macramê",
      "Mural de Fotos",
      "Arte Digital em Tela / Canvas",
      "Miniaturas / Dioramas",
      "Funko Pops",
      "Action Figures",
      "LEGO",
      "Hot Wheels / Diecast",
      "Coleção de Consoles",
      "Coleção de Controles",
      "Coleção de Teclados",
      "Cards / TCG (Pokémon, etc.)",
      "Mangás / HQs",
      "Vinil / Discos",
      "Cable Management Impecável",
      "Calha de Cabos",
      "Cabos Personalizados / Coiled",
      "Sem Fio Nenhum (100% wireless)",
      "Velcro Organizado",
      "Desk Cable Tray",
      "Passa Fio na Mesa",
      "Cable Sleeve",
      "Setup com Caixas de Som",
      "Monitores de Áudio",
      "Soundbar",
      "Subwoofer",
      "Fones de Ouvido em Destaque",
      "Headphone Stand / Suporte",
      "Setup Hi-Fi",
      "Microfone Profissional",
      "Boom Arm / Braço de Microfone",
      "Interface de Áudio Visível",
      "Setup com Vitrola",
      "Teclado Mecânico Custom",
      "Teclado 60% / 65% / 75%",
      "Teclado Full Size",
      "Teclado Split / Ergonômico",
      "Mouse Premium",
      "Mousepad Full Desk",
      "Mousepad RGB",
      "Deskmat Temático",
      "Webcam Setup",
      "Stream Deck",
      "Trackpad",
      "Mesa Digitalizadora / Wacom",
      "Pegboard",
      "Prateleiras Flutuantes",
      "Estante / Bookshelf",
      "Gavetas Organizadoras",
      "Bandeja de Mesa / Desk Tray",
      "Organizador de Cabos",
      "Porta-Canetas",
      "Dock Station",
      "Monitor Stand / Suporte de Monitor",
      "Laptop Stand",
      "Cadeira Gamer",
      "Cadeira Ergonômica",
      "Cadeira de Escritório Clássica",
      "Cadeira Herman Miller / Premium",
      "Cadeira de Madeira",
      "Banco / Stool",
      "Cadeira com Apoio de Pé",
      "Ventilador de Mesa",
      "Umidificador",
      "Purificador de Ar",
      "Difusor de Aromas",
      "Setup com Cantinho do Café",
      "Cafeteira na Mesa",
      "Copo / Caneca Temática",
      "Garrafa Térmica",
      "Mini Geladeira",
      "Porta-Copos",
      "Aquecedor de Caneca",
      "HomePod / Smart Speaker",
      "Echo Dot / Alexa",
      "Carregador Wireless",
      "Dock pra Celular",
      "Apple Watch Charger",
      "iPad como Segunda Tela",
      "Tablet na Mesa",
      "E-reader / Kindle",
      "Câmera Mirrorless no Setup",
      "Painéis Acústicos",
      "Espuma Acústica",
      "Difusores",
      "Cortina Blackout",
      "Carpete / Tapete",
      "Bass Trap",
      "Papel de Parede",
      "Pintura Diferenciada",
      "Parede Colorida (accent wall)",
      "Tijolo Aparente",
      "Parede de Madeira / Ripado",
      "Painel 3D",
      "Painel de LED na Parede",
      "Greenscreen / Fundo pra Stream",
      "Apoio de Pé / Footrest",
      "Apoio de Punho / Wrist Rest",
      "Suporte Ergonômico de Monitor",
      "Almofada Lombar",
      "Tapete Anti-Fadiga",
      "Controle por Voz",
      "Automação de Luz",
      "Tomada Smart",
      "Sensor de Presença",
      "Painel de Controle Smart Home",
      "Console em Destaque (PS5, Xbox, Switch)",
      "Arcade Stick / Fightstick",
      "Racing Wheel / Volante",
      "Sim Rig",
      "VR Headset",
      "Retro Gaming",
      "Handheld (Steam Deck, ROG Ally)",
      "Pet no Setup (gato, cachorro)",
      "Cama de Pet na Mesa",
      "Skate na Parede",
      "Instrumento Musical",
      "Guitarra na Parede",
      "Bicicleta no Ambiente",
      "Prancha de Surf",
      "Troféus / Medalhas",
      "Diploma na Parede",
    ],
  },
  {
    nome: "Por Orçamento",
    slug: "orcamento",
    ordem: 6,
    categorias: [
      "Budget / Econômico",
      "Custo-Benefício",
      "Intermediário",
      "High-End / Premium",
      "Ultra Premium / Sem Limite",
      "Luxo / Ostentação",
      "Investimento Único",
      "Setup Evolutivo (upgrade gradual)",
      "Setup Modular (troca peças)",
      "Minimalista Econômico",
      "Buy Once, Cry Once",
      "Melhor Retorno por Real",
      "Foco em 1 Item Premium",
    ],
  },
];

async function main() {
  console.log("Seeding database with category groups...");

  let totalCategorias = 0;

  for (const grupo of gruposData) {
    // Criar ou atualizar o grupo
    const grupoCategoria = await prisma.grupoCategoria.upsert({
      where: { slug: grupo.slug },
      update: {
        nome: grupo.nome,
        ordem: grupo.ordem,
      },
      create: {
        nome: grupo.nome,
        slug: grupo.slug,
        ordem: grupo.ordem,
      },
    });

    console.log(`Created/updated group: ${grupo.nome}`);

    // Criar ou atualizar as categorias do grupo
    for (let i = 0; i < grupo.categorias.length; i++) {
      const categoriaNome = grupo.categorias[i];
      const categoriaSlug = slugify(categoriaNome);

      await prisma.categoria.upsert({
        where: { slug: categoriaSlug },
        update: {
          nome: categoriaNome,
          ordem: i + 1,
          grupoId: grupoCategoria.id,
        },
        create: {
          nome: categoriaNome,
          slug: categoriaSlug,
          ordem: i + 1,
          grupoId: grupoCategoria.id,
        },
      });

      totalCategorias++;
    }
  }

  console.log(`Created/updated ${gruposData.length} groups`);
  console.log(`Created/updated ${totalCategorias} categories`);
  console.log("Seeding completed!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
