import type { SetupWithRelations, Categoria } from "@/types";

// Dados mock para desenvolvimento sem banco de dados
export const mockCategorias: Categoria[] = [
  {
    id: "cat-1",
    nome: "Minimalista",
    slug: "minimalista",
    descricao: "Setups limpos e organizados com o essencial",
    cor: "#10b981",
    icone: "Sparkles",
    ordem: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-2",
    nome: "Moderno",
    slug: "moderno",
    descricao: "Designs contemporâneos com tecnologia de ponta",
    cor: "#3b82f6",
    icone: "Monitor",
    ordem: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-3",
    nome: "Gamer",
    slug: "gamer",
    descricao: "Setups otimizados para gaming com RGB e performance",
    cor: "#ef4444",
    icone: "Gamepad2",
    ordem: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-4",
    nome: "Trabalho",
    slug: "trabalho",
    descricao: "Workspaces produtivos para home office",
    cor: "#f59e0b",
    icone: "Briefcase",
    ordem: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-5",
    nome: "Estiloso",
    slug: "estiloso",
    descricao: "Setups com design único e personalidade",
    cor: "#ec4899",
    icone: "Palette",
    ordem: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-6",
    nome: "Escuro",
    slug: "escuro",
    descricao: "Ambientes dark com iluminação ambiente",
    cor: "#6366f1",
    icone: "Moon",
    ordem: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-7",
    nome: "Claro",
    slug: "claro",
    descricao: "Espaços luminosos e clean",
    cor: "#fbbf24",
    icone: "Sun",
    ordem: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-8",
    nome: "Amadeirado",
    slug: "amadeirado",
    descricao: "Setups com elementos de madeira natural",
    cor: "#a16207",
    icone: "TreePine",
    ordem: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockSetups: SetupWithRelations[] = [
  {
    id: "setup-1",
    titulo: "Setup Minimalista Clean",
    descricao:
      "Um setup extremamente limpo e organizado, perfeito para quem busca foco e produtividade sem distrações visuais.",
    imagemUrl:
      "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Lucas Silva",
    fonte: "Instagram",
    fonteUrl: "https://instagram.com",
    destaque: true,
    visualizacoes: 1250,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[0], mockCategorias[6], mockCategorias[3]],
    produtos: [
      {
        id: "prod-1-1",
        nome: 'Apple Studio Display 27"',
        descricao: "Monitor 5K Retina com webcam integrada",
        categoria: "Monitor",
        preco: 11999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: true,
        ordem: 0,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-2",
        nome: "MacBook Pro M3 14 polegadas",
        descricao: "Notebook Apple com chip M3",
        categoria: "Notebook",
        preco: 18999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-3",
        nome: "Magic Keyboard com Touch ID",
        descricao: null,
        categoria: "Teclado",
        preco: 1599,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 2,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-4",
        nome: "Magic Trackpad",
        descricao: null,
        categoria: "Mouse/Trackpad",
        preco: 1099,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 3,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-5",
        nome: "Mesa Sit-Stand FlexDesk",
        descricao: "Mesa com ajuste de altura elétrico",
        categoria: "Mesa",
        preco: 2499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://anmasetups.com.br",
        loja: "ANMA Setups",
        destaque: false,
        ordem: 4,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-2",
    titulo: "Gaming Battlestation RGB",
    descricao:
      "Setup gamer completo com iluminação RGB sincronizada, dual monitor e cadeira ergonômica para longas sessões.",
    imagemUrl:
      "https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Pedro Gamer",
    fonte: "Twitter",
    fonteUrl: "https://twitter.com",
    destaque: true,
    visualizacoes: 2340,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[2], mockCategorias[5], mockCategorias[1]],
    produtos: [
      {
        id: "prod-2-1",
        nome: 'LG UltraGear 27" 165Hz',
        descricao: "Monitor gaming com alta taxa de atualização",
        categoria: "Monitor",
        preco: 2299,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: true,
        ordem: 0,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-2",
        nome: 'Monitor Secundário 24" 144Hz',
        descricao: null,
        categoria: "Monitor",
        preco: 1299,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: false,
        ordem: 1,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-3",
        nome: "Razer BlackWidow V4 Pro",
        descricao: "Teclado mecânico com switches Razer",
        categoria: "Teclado",
        preco: 1899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://razer.com",
        loja: "Razer",
        destaque: false,
        ordem: 2,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-4",
        nome: "Logitech G Pro X Superlight 2",
        descricao: "Mouse ultra leve para esports",
        categoria: "Mouse",
        preco: 899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-5",
        nome: "HyperX QuadCast S",
        descricao: "Microfone USB com RGB",
        categoria: "Microfone",
        preco: 799,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-6",
        nome: "Secretlab Titan Evo 2024",
        descricao: "Cadeira gamer premium",
        categoria: "Cadeira",
        preco: 3499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://secretlab.co",
        loja: "Secretlab",
        destaque: false,
        ordem: 5,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-3",
    titulo: "Home Office Produtivo",
    descricao:
      "Workspace profissional para trabalho remoto com dois monitores, iluminação adequada e organização impecável.",
    imagemUrl:
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Maria Santos",
    fonte: "Pinterest",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 890,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[3], mockCategorias[1], mockCategorias[6]],
    produtos: [
      {
        id: "prod-3-1",
        nome: 'Dell UltraSharp U2723QE 27"',
        descricao: "Monitor 4K com USB-C Hub",
        categoria: "Monitor",
        preco: 4999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://dell.com.br",
        loja: "Dell",
        destaque: true,
        ordem: 0,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-2",
        nome: 'Monitor Vertical 24"',
        descricao: null,
        categoria: "Monitor",
        preco: 899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: false,
        ordem: 1,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-3",
        nome: "Keychron K8 Pro",
        descricao: "Teclado mecânico sem fio",
        categoria: "Teclado",
        preco: 599,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-4",
        nome: "Logitech MX Master 3S",
        descricao: "Mouse ergonômico premium",
        categoria: "Mouse",
        preco: 599,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-5",
        nome: "Webcam Logitech Brio 4K",
        descricao: "Webcam profissional 4K HDR",
        categoria: "Webcam",
        preco: 1199,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-4",
    titulo: "Setup Amadeirado Aconchegante",
    descricao:
      "Combinação perfeita de tecnologia com elementos naturais de madeira, criando um ambiente acolhedor.",
    imagemUrl:
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Ana Carvalho",
    fonte: "Instagram",
    fonteUrl: "https://instagram.com",
    destaque: false,
    visualizacoes: 756,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[7], mockCategorias[4], mockCategorias[0]],
    produtos: [
      {
        id: "prod-4-1",
        nome: "Mesa de Madeira Maciça 160cm",
        descricao: "Mesa artesanal de madeira de demolição",
        categoria: "Mesa",
        preco: 1899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://anmasetups.com.br",
        loja: "ANMA Setups",
        destaque: true,
        ordem: 0,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-4-2",
        nome: 'iMac 24" M3',
        descricao: "All-in-one Apple com chip M3",
        categoria: "Computador",
        preco: 13499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-4-3",
        nome: "Luminária de Mesa Articulada",
        descricao: null,
        categoria: "Iluminação",
        preco: 399,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://tokstok.com.br",
        loja: "Tok&Stok",
        destaque: false,
        ordem: 2,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-4-4",
        nome: "Organizador de Mesa em Bambu",
        descricao: "Organizador sustentável",
        categoria: "Organização",
        preco: 129,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-5",
    titulo: "Developer Dark Setup",
    descricao:
      "Setup focado em desenvolvimento de software com tema escuro, múltiplos monitores e teclado mecânico premium.",
    imagemUrl:
      "https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Rafael Dev",
    fonte: "Twitter",
    fonteUrl: null,
    destaque: true,
    visualizacoes: 1890,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[5], mockCategorias[3], mockCategorias[1]],
    produtos: [
      {
        id: "prod-5-1",
        nome: 'LG DualUp 28" Ergo',
        descricao: "Monitor vertical 16:18 para produtividade",
        categoria: "Monitor",
        preco: 5999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://lg.com/br",
        loja: "LG",
        destaque: true,
        ordem: 0,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-2",
        nome: 'Monitor Ultrawide 34"',
        descricao: "Ultrawide curvo para imersão",
        categoria: "Monitor",
        preco: 3499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: false,
        ordem: 1,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-3",
        nome: "ZSA Moonlander Mark I",
        descricao: "Teclado split ergonômico programável",
        categoria: "Teclado",
        preco: 2499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://zsa.io",
        loja: "ZSA",
        destaque: false,
        ordem: 2,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-4",
        nome: "Logitech MX Vertical",
        descricao: "Mouse ergonômico vertical",
        categoria: "Mouse",
        preco: 499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-5",
        nome: "Sony WH-1000XM5",
        descricao: "Headphone com cancelamento de ruído",
        categoria: "Headphone",
        preco: 2299,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-6",
    titulo: "Setup Criativo para Design",
    descricao:
      "Workspace perfeito para designers e criativos, com tablet gráfico, monitor calibrado e organização inspiradora.",
    imagemUrl:
      "https://images.unsplash.com/photo-1542744094-24638eff58bb?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Julia Design",
    fonte: "Behance",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 654,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[4], mockCategorias[6], mockCategorias[3]],
    produtos: [
      {
        id: "prod-6-1",
        nome: 'ASUS ProArt PA279CV 27"',
        descricao: "Monitor 4K calibrado para design",
        categoria: "Monitor",
        preco: 3299,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: true,
        ordem: 0,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-6-2",
        nome: "Wacom Cintiq 16",
        descricao: "Tablet gráfico com tela",
        categoria: "Tablet Gráfico",
        preco: 4999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://wacom.com",
        loja: "Wacom",
        destaque: false,
        ordem: 1,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-6-3",
        nome: "Logitech Craft",
        descricao: "Teclado com dial criativo",
        categoria: "Teclado",
        preco: 899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-6-4",
        nome: "Luminária BenQ ScreenBar",
        descricao: "Luminária para monitor",
        categoria: "Iluminação",
        preco: 899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-7",
    titulo: "Streaming Setup Profissional",
    descricao:
      "Setup completo para streaming e criação de conteúdo com iluminação ring light, microfone profissional e câmera 4K.",
    imagemUrl:
      "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80",
    videoUrl: null,
    isVideo: true,
    autor: "Carlos Stream",
    fonte: "Twitch",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 1456,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[2], mockCategorias[5], mockCategorias[4]],
    produtos: [
      {
        id: "prod-7-1",
        nome: "Sony A6400 + Lente 16-50mm",
        descricao: "Câmera mirrorless para streaming",
        categoria: "Câmera",
        preco: 7999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: true,
        ordem: 0,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-2",
        nome: "Elgato Key Light Air (par)",
        descricao: "Iluminação profissional para streaming",
        categoria: "Iluminação",
        preco: 1999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 1,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-3",
        nome: "Shure SM7B",
        descricao: "Microfone dinâmico profissional",
        categoria: "Microfone",
        preco: 3499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-4",
        nome: "GoXLR Mini",
        descricao: "Interface de áudio para streaming",
        categoria: "Interface de Áudio",
        preco: 1799,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-5",
        nome: "Elgato Stream Deck MK.2",
        descricao: "Controlador de streaming",
        categoria: "Controlador",
        preco: 999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-8",
    titulo: "Setup Compacto para Apartamento",
    descricao:
      "Solução inteligente para espaços pequenos, maximizando produtividade em ambientes reduzidos.",
    imagemUrl:
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Fernanda Lima",
    fonte: "Pinterest",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 432,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[0], mockCategorias[1], mockCategorias[3]],
    produtos: [
      {
        id: "prod-8-1",
        nome: "Mesa Dobrável de Parede",
        descricao: "Mesa compacta que dobra na parede",
        categoria: "Mesa",
        preco: 799,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://anmasetups.com.br",
        loja: "ANMA Setups",
        destaque: true,
        ordem: 0,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-8-2",
        nome: "MacBook Air M3",
        descricao: "Notebook ultrafino Apple",
        categoria: "Notebook",
        preco: 12999,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-8-3",
        nome: "Hub USB-C 10 em 1",
        descricao: "Hub multiportas compacto",
        categoria: "Acessório",
        preco: 299,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-8-4",
        nome: "Suporte para Notebook",
        descricao: "Suporte ajustável de alumínio",
        categoria: "Suporte",
        preco: 199,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-9",
    titulo: "Setup Retro Gaming",
    descricao:
      "Homenagem aos clássicos com visual retrô moderno, incluindo consoles vintage e decoração nostálgica.",
    imagemUrl:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Thiago Retro",
    fonte: "Reddit",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 987,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[2], mockCategorias[4]],
    produtos: [
      {
        id: "prod-9-1",
        nome: 'TV CRT Sony 21"',
        descricao: "TV de tubo original para retrogaming",
        categoria: "TV",
        preco: 599,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://olx.com.br",
        loja: "OLX",
        destaque: true,
        ordem: 0,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-9-2",
        nome: "Nintendo 64 Original",
        descricao: "Console Nintendo 64 completo",
        categoria: "Console",
        preco: 899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://mercadolivre.com.br",
        loja: "Mercado Livre",
        destaque: false,
        ordem: 1,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-9-3",
        nome: "Super Nintendo Original",
        descricao: "Console SNES completo",
        categoria: "Console",
        preco: 699,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://mercadolivre.com.br",
        loja: "Mercado Livre",
        destaque: false,
        ordem: 2,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-9-4",
        nome: "Estante Retrô para Games",
        descricao: "Estante vintage para colecionáveis",
        categoria: "Móvel",
        preco: 499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-10",
    titulo: "Setup Ultra Clean White",
    descricao:
      "Todo em branco, esse setup é o ápice do minimalismo com cada detalhe pensado para harmonia visual.",
    imagemUrl:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
    videoUrl: null,
    isVideo: false,
    autor: "Camila White",
    fonte: "Instagram",
    fonteUrl: "https://instagram.com",
    destaque: false,
    visualizacoes: 1123,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[0], mockCategorias[6], mockCategorias[1]],
    produtos: [
      {
        id: "prod-10-1",
        nome: 'Samsung Smart Monitor M8 32"',
        descricao: "Monitor smart 4K com Tizen",
        categoria: "Monitor",
        preco: 4499,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://samsung.com/br",
        loja: "Samsung",
        destaque: true,
        ordem: 0,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-2",
        nome: "Apple Magic Keyboard (Branco)",
        descricao: null,
        categoria: "Teclado",
        preco: 1099,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-3",
        nome: "Apple Magic Mouse (Branco)",
        descricao: null,
        categoria: "Mouse",
        preco: 699,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 2,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-4",
        nome: "Mesa Branca 140cm",
        descricao: "Mesa minimalista branca",
        categoria: "Mesa",
        preco: 899,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://ikea.com/br",
        loja: "IKEA",
        destaque: false,
        ordem: 3,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-5",
        nome: "Cadeira Eames Branca",
        descricao: "Cadeira design clássico",
        categoria: "Cadeira",
        preco: 799,
        moeda: "BRL",
        imagemUrl: null,
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];

// Funções para obter dados mock
export function getMockSetups(): SetupWithRelations[] {
  return mockSetups;
}

export function getMockSetupById(id: string): SetupWithRelations | null {
  return mockSetups.find((s) => s.id === id) || null;
}

export function getMockCategorias(): Categoria[] {
  return mockCategorias;
}

export function getMockCategoriaBySlug(slug: string) {
  const categoria = mockCategorias.find((c) => c.slug === slug);
  if (!categoria) return null;

  const setups = mockSetups.filter((s) =>
    s.categorias.some((c) => c.slug === slug)
  );

  return {
    ...categoria,
    setups,
  };
}
