import type { SetupWithRelations, Categoria } from "@/types";

// Dados mock para desenvolvimento sem banco de dados
export const mockCategorias: Categoria[] = [
  {
    id: "cat-1",
    nome: "Minimalista",
    slug: "minimalista",
    descricao: "Setups limpos e organizados com o essencial",
    cor: "#10b981",
    icone: "Sparkles",
    ordem: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-2",
    nome: "Moderno",
    slug: "moderno",
    descricao: "Designs contemporâneos com tecnologia de ponta",
    cor: "#3b82f6",
    icone: "Monitor",
    ordem: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-3",
    nome: "Gamer",
    slug: "gamer",
    descricao: "Setups otimizados para gaming com RGB e performance",
    cor: "#ef4444",
    icone: "Gamepad2",
    ordem: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-4",
    nome: "Trabalho",
    slug: "trabalho",
    descricao: "Workspaces produtivos para home office",
    cor: "#f59e0b",
    icone: "Briefcase",
    ordem: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-5",
    nome: "Estiloso",
    slug: "estiloso",
    descricao: "Setups com design único e personalidade",
    cor: "#ec4899",
    icone: "Palette",
    ordem: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-6",
    nome: "Escuro",
    slug: "escuro",
    descricao: "Ambientes dark com iluminação ambiente",
    cor: "#6366f1",
    icone: "Moon",
    ordem: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-7",
    nome: "Claro",
    slug: "claro",
    descricao: "Espaços luminosos e clean",
    cor: "#fbbf24",
    icone: "Sun",
    ordem: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat-8",
    nome: "Amadeirado",
    slug: "amadeirado",
    descricao: "Setups com elementos de madeira natural",
    cor: "#a16207",
    icone: "TreePine",
    ordem: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockSetups: SetupWithRelations[] = [
  {
    id: "setup-1",
    titulo: "Setup Minimalista Clean",
    descricao:
      "Um setup extremamente limpo e organizado, perfeito para quem busca foco e produtividade sem distrações visuais.",
    imagemUrl:
      "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80",
    imagens: [
      "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
      "https://images.unsplash.com/photo-1600494603989-9650cf6ddd3d?w=800&q=80",
      "https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=800&q=80",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
      "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&q=80",
      "https://images.unsplash.com/photo-1547082299-de196ea013d6?w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
      "https://images.unsplash.com/photo-1537498425277-c283d32ef9db?w=800&q=80",
    ],
    videoUrl: null,
    isVideo: false,
    autor: "Lucas Silva",
    fonte: "Instagram",
    fonteUrl: "https://instagram.com",
    destaque: true,
    visualizacoes: 1250,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[0], mockCategorias[6], mockCategorias[3]],
    produtos: [
      {
        id: "prod-1-1",
        nome: 'Apple Studio Display 27"',
        descricao: "Monitor 5K Retina com webcam integrada",
        categoria: "Monitor",
        imagemUrl: null,
        preco: 11999,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: true,
        ordem: 0,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-2",
        nome: "MacBook Pro M3 14 polegadas",
        descricao: "Notebook Apple com chip M3",
        categoria: "Notebook",
        imagemUrl: null,
        preco: 18999,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-3",
        nome: "Magic Keyboard com Touch ID",
        descricao: null,
        categoria: "Teclado",
        imagemUrl: null,
        preco: 1599,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 2,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-4",
        nome: "Magic Trackpad",
        descricao: null,
        categoria: "Mouse/Trackpad",
        imagemUrl: null,
        preco: 1099,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 3,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-1-5",
        nome: "Mesa Sit-Stand FlexDesk",
        descricao: "Mesa com ajuste de altura elétrico",
        categoria: "Mesa",
        imagemUrl: null,
        preco: 2499,
        moeda: "BRL",
        linkCompra: "https://anmasetups.com.br",
        loja: "ANMA Setups",
        destaque: false,
        ordem: 4,
        setupId: "setup-1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-2",
    titulo: "Gaming Battlestation RGB",
    descricao:
      "Setup gamer completo com iluminação RGB sincronizada, dual monitor e cadeira ergonômica para longas sessões.",
    imagemUrl:
      "https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Pedro Gamer",
    fonte: "Twitter",
    fonteUrl: "https://twitter.com",
    destaque: true,
    visualizacoes: 2340,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[2], mockCategorias[5], mockCategorias[1]],
    produtos: [
      {
        id: "prod-2-1",
        nome: 'LG UltraGear 27" 165Hz',
        descricao: "Monitor gaming com alta taxa de atualização",
        categoria: "Monitor",
        imagemUrl: null,
        preco: 2299,
        moeda: "BRL",
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: true,
        ordem: 0,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-2",
        nome: 'Monitor Secundário 24" 144Hz',
        descricao: null,
        categoria: "Monitor",
        imagemUrl: null,
        preco: 1299,
        moeda: "BRL",
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: false,
        ordem: 1,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-3",
        nome: "Razer BlackWidow V4 Pro",
        descricao: "Teclado mecânico com switches Razer",
        categoria: "Teclado",
        imagemUrl: null,
        preco: 1899,
        moeda: "BRL",
        linkCompra: "https://razer.com",
        loja: "Razer",
        destaque: false,
        ordem: 2,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-4",
        nome: "Logitech G Pro X Superlight 2",
        descricao: "Mouse ultra leve para esports",
        categoria: "Mouse",
        imagemUrl: null,
        preco: 899,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-5",
        nome: "HyperX QuadCast S",
        descricao: "Microfone USB com RGB",
        categoria: "Microfone",
        imagemUrl: null,
        preco: 799,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-2-6",
        nome: "Secretlab Titan Evo 2024",
        descricao: "Cadeira gamer premium",
        categoria: "Cadeira",
        imagemUrl: null,
        preco: 3499,
        moeda: "BRL",
        linkCompra: "https://secretlab.co",
        loja: "Secretlab",
        destaque: false,
        ordem: 5,
        setupId: "setup-2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-3",
    titulo: "Home Office Produtivo",
    descricao:
      "Workspace profissional para trabalho remoto com dois monitores, iluminação adequada e organização impecável.",
    imagemUrl:
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Maria Santos",
    fonte: "Pinterest",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 890,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[3], mockCategorias[1], mockCategorias[6]],
    produtos: [
      {
        id: "prod-3-1",
        nome: 'Dell UltraSharp U2723QE 27"',
        descricao: "Monitor 4K com USB-C Hub",
        categoria: "Monitor",
        imagemUrl: null,
        preco: 4999,
        moeda: "BRL",
        linkCompra: "https://dell.com.br",
        loja: "Dell",
        destaque: true,
        ordem: 0,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-2",
        nome: 'Monitor Vertical 24"',
        descricao: null,
        categoria: "Monitor",
        imagemUrl: null,
        preco: 899,
        moeda: "BRL",
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: false,
        ordem: 1,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-3",
        nome: "Keychron K8 Pro",
        descricao: "Teclado mecânico sem fio",
        categoria: "Teclado",
        imagemUrl: null,
        preco: 599,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-4",
        nome: "Logitech MX Master 3S",
        descricao: "Mouse ergonômico premium",
        categoria: "Mouse",
        imagemUrl: null,
        preco: 599,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-3-5",
        nome: "Webcam Logitech Brio 4K",
        descricao: "Webcam profissional 4K HDR",
        categoria: "Webcam",
        imagemUrl: null,
        preco: 1199,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-4",
    titulo: "Setup Amadeirado Aconchegante",
    descricao:
      "Combinação perfeita de tecnologia com elementos naturais de madeira, criando um ambiente acolhedor.",
    imagemUrl:
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Ana Carvalho",
    fonte: "Instagram",
    fonteUrl: "https://instagram.com",
    destaque: false,
    visualizacoes: 756,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[7], mockCategorias[4], mockCategorias[0]],
    produtos: [
      {
        id: "prod-4-1",
        nome: "Mesa de Madeira Maciça 160cm",
        descricao: "Mesa artesanal de madeira de demolição",
        categoria: "Mesa",
        imagemUrl: null,
        preco: 1899,
        moeda: "BRL",
        linkCompra: "https://anmasetups.com.br",
        loja: "ANMA Setups",
        destaque: true,
        ordem: 0,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-4-2",
        nome: 'iMac 24" M3',
        descricao: "All-in-one Apple com chip M3",
        categoria: "Computador",
        imagemUrl: null,
        preco: 13499,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-4-3",
        nome: "Luminária de Mesa Articulada",
        descricao: null,
        categoria: "Iluminação",
        imagemUrl: null,
        preco: 399,
        moeda: "BRL",
        linkCompra: "https://tokstok.com.br",
        loja: "Tok&Stok",
        destaque: false,
        ordem: 2,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-4-4",
        nome: "Organizador de Mesa em Bambu",
        descricao: "Organizador sustentável",
        categoria: "Organização",
        imagemUrl: null,
        preco: 129,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-5",
    titulo: "Developer Dark Setup",
    descricao:
      "Setup focado em desenvolvimento de software com tema escuro, múltiplos monitores e teclado mecânico premium.",
    imagemUrl:
      "https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Rafael Dev",
    fonte: "Twitter",
    fonteUrl: null,
    destaque: true,
    visualizacoes: 1890,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[5], mockCategorias[3], mockCategorias[1]],
    produtos: [
      {
        id: "prod-5-1",
        nome: 'LG DualUp 28" Ergo',
        descricao: "Monitor vertical 16:18 para produtividade",
        categoria: "Monitor",
        imagemUrl: null,
        preco: 5999,
        moeda: "BRL",
        linkCompra: "https://lg.com/br",
        loja: "LG",
        destaque: true,
        ordem: 0,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-2",
        nome: 'Monitor Ultrawide 34"',
        descricao: "Ultrawide curvo para imersão",
        categoria: "Monitor",
        imagemUrl: null,
        preco: 3499,
        moeda: "BRL",
        linkCompra: "https://kabum.com.br",
        loja: "Kabum",
        destaque: false,
        ordem: 1,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-3",
        nome: "ZSA Moonlander Mark I",
        descricao: "Teclado split ergonômico programável",
        categoria: "Teclado",
        imagemUrl: null,
        preco: 2499,
        moeda: "BRL",
        linkCompra: "https://zsa.io",
        loja: "ZSA",
        destaque: false,
        ordem: 2,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-4",
        nome: "Logitech MX Vertical",
        descricao: "Mouse ergonômico vertical",
        categoria: "Mouse",
        imagemUrl: null,
        preco: 499,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-5-5",
        nome: "Sony WH-1000XM5",
        descricao: "Headphone com cancelamento de ruído",
        categoria: "Headphone",
        imagemUrl: null,
        preco: 2299,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-6",
    titulo: "Setup Criativo para Design",
    descricao:
      "Workspace perfeito para designers e criativos, com tablet gráfico, monitor calibrado e organização inspiradora.",
    imagemUrl:
      "https://images.unsplash.com/photo-1542744094-24638eff58bb?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Julia Design",
    fonte: "Behance",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 654,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[4], mockCategorias[6], mockCategorias[3]],
    produtos: [
      {
        id: "prod-6-1",
        nome: 'ASUS ProArt PA279CV 27"',
        descricao: "Monitor 4K calibrado para design",
        categoria: "Monitor",
        imagemUrl: null,
        preco: 3299,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: true,
        ordem: 0,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-6-2",
        nome: "Wacom Cintiq 16",
        descricao: "Tablet gráfico com tela",
        categoria: "Tablet Gráfico",
        imagemUrl: null,
        preco: 4999,
        moeda: "BRL",
        linkCompra: "https://wacom.com",
        loja: "Wacom",
        destaque: false,
        ordem: 1,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-6-3",
        nome: "Logitech Craft",
        descricao: "Teclado com dial criativo",
        categoria: "Teclado",
        imagemUrl: null,
        preco: 899,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-6-4",
        nome: "Luminária BenQ ScreenBar",
        descricao: "Luminária para monitor",
        categoria: "Iluminação",
        imagemUrl: null,
        preco: 899,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-6",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-7",
    titulo: "Streaming Setup Profissional",
    descricao:
      "Setup completo para streaming e criação de conteúdo com iluminação ring light, microfone profissional e câmera 4K.",
    imagemUrl:
      "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: true,
    autor: "Carlos Stream",
    fonte: "Twitch",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 1456,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[2], mockCategorias[5], mockCategorias[4]],
    produtos: [
      {
        id: "prod-7-1",
        nome: "Sony A6400 + Lente 16-50mm",
        descricao: "Câmera mirrorless para streaming",
        categoria: "Câmera",
        imagemUrl: null,
        preco: 7999,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: true,
        ordem: 0,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-2",
        nome: "Elgato Key Light Air (par)",
        descricao: "Iluminação profissional para streaming",
        categoria: "Iluminação",
        imagemUrl: null,
        preco: 1999,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 1,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-3",
        nome: "Shure SM7B",
        descricao: "Microfone dinâmico profissional",
        categoria: "Microfone",
        imagemUrl: null,
        preco: 3499,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-4",
        nome: "GoXLR Mini",
        descricao: "Interface de áudio para streaming",
        categoria: "Interface de Áudio",
        imagemUrl: null,
        preco: 1799,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-7-5",
        nome: "Elgato Stream Deck MK.2",
        descricao: "Controlador de streaming",
        categoria: "Controlador",
        imagemUrl: null,
        preco: 999,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-7",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-8",
    titulo: "Setup Compacto para Apartamento",
    descricao:
      "Solução inteligente para espaços pequenos, maximizando produtividade em ambientes reduzidos.",
    imagemUrl:
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Fernanda Lima",
    fonte: "Pinterest",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 432,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[0], mockCategorias[1], mockCategorias[3]],
    produtos: [
      {
        id: "prod-8-1",
        nome: "Mesa Dobrável de Parede",
        descricao: "Mesa compacta que dobra na parede",
        categoria: "Mesa",
        imagemUrl: null,
        preco: 799,
        moeda: "BRL",
        linkCompra: "https://anmasetups.com.br",
        loja: "ANMA Setups",
        destaque: true,
        ordem: 0,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-8-2",
        nome: "MacBook Air M3",
        descricao: "Notebook ultrafino Apple",
        categoria: "Notebook",
        imagemUrl: null,
        preco: 12999,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-8-3",
        nome: "Hub USB-C 10 em 1",
        descricao: "Hub multiportas compacto",
        categoria: "Acessório",
        imagemUrl: null,
        preco: 299,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 2,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-8-4",
        nome: "Suporte para Notebook",
        descricao: "Suporte ajustável de alumínio",
        categoria: "Suporte",
        imagemUrl: null,
        preco: 199,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-8",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-9",
    titulo: "Setup Retro Gaming",
    descricao:
      "Homenagem aos clássicos com visual retrô moderno, incluindo consoles vintage e decoração nostálgica.",
    imagemUrl:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Thiago Retro",
    fonte: "Reddit",
    fonteUrl: null,
    destaque: false,
    visualizacoes: 987,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[2], mockCategorias[4]],
    produtos: [
      {
        id: "prod-9-1",
        nome: 'TV CRT Sony 21"',
        descricao: "TV de tubo original para retrogaming",
        categoria: "TV",
        imagemUrl: null,
        preco: 599,
        moeda: "BRL",
        linkCompra: "https://olx.com.br",
        loja: "OLX",
        destaque: true,
        ordem: 0,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-9-2",
        nome: "Nintendo 64 Original",
        descricao: "Console Nintendo 64 completo",
        categoria: "Console",
        imagemUrl: null,
        preco: 899,
        moeda: "BRL",
        linkCompra: "https://mercadolivre.com.br",
        loja: "Mercado Livre",
        destaque: false,
        ordem: 1,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-9-3",
        nome: "Super Nintendo Original",
        descricao: "Console SNES completo",
        categoria: "Console",
        imagemUrl: null,
        preco: 699,
        moeda: "BRL",
        linkCompra: "https://mercadolivre.com.br",
        loja: "Mercado Livre",
        destaque: false,
        ordem: 2,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-9-4",
        nome: "Estante Retrô para Games",
        descricao: "Estante vintage para colecionáveis",
        categoria: "Móvel",
        imagemUrl: null,
        preco: 499,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 3,
        setupId: "setup-9",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "setup-10",
    titulo: "Setup Ultra Clean White",
    descricao:
      "Todo em branco, esse setup é o ápice do minimalismo com cada detalhe pensado para harmonia visual.",
    imagemUrl:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
    imagens: [],
    videoUrl: null,
    isVideo: false,
    autor: "Camila White",
    fonte: "Instagram",
    fonteUrl: "https://instagram.com",
    destaque: false,
    visualizacoes: 1123,
    createdAt: new Date(),
    updatedAt: new Date(),
    categorias: [mockCategorias[0], mockCategorias[6], mockCategorias[1]],
    produtos: [
      {
        id: "prod-10-1",
        nome: 'Samsung Smart Monitor M8 32"',
        descricao: "Monitor smart 4K com Tizen",
        categoria: "Monitor",
        imagemUrl: null,
        preco: 4499,
        moeda: "BRL",
        linkCompra: "https://samsung.com/br",
        loja: "Samsung",
        destaque: true,
        ordem: 0,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-2",
        nome: "Apple Magic Keyboard (Branco)",
        descricao: null,
        categoria: "Teclado",
        imagemUrl: null,
        preco: 1099,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 1,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-3",
        nome: "Apple Magic Mouse (Branco)",
        descricao: null,
        categoria: "Mouse",
        imagemUrl: null,
        preco: 699,
        moeda: "BRL",
        linkCompra: "https://apple.com/br",
        loja: "Apple Store",
        destaque: false,
        ordem: 2,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-4",
        nome: "Mesa Branca 140cm",
        descricao: "Mesa minimalista branca",
        categoria: "Mesa",
        imagemUrl: null,
        preco: 899,
        moeda: "BRL",
        linkCompra: "https://ikea.com/br",
        loja: "IKEA",
        destaque: false,
        ordem: 3,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "prod-10-5",
        nome: "Cadeira Eames Branca",
        descricao: "Cadeira design clássico",
        categoria: "Cadeira",
        imagemUrl: null,
        preco: 799,
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: "Amazon",
        destaque: false,
        ordem: 4,
        setupId: "setup-10",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  // Setups adicionais para visualização
  ...generateAdditionalSetups(),
];

// Função para gerar setups adicionais
function generateAdditionalSetups(): SetupWithRelations[] {
  const setupTemplates = [
    { titulo: "Setup Neon Purple", img: "photo-1600585154340-be6161a56a0c", cats: [5, 2, 4] },
    { titulo: "Workspace Escandinavo", img: "photo-1618005198919-d3d4b5a92ead", cats: [0, 6, 7] },
    { titulo: "Gaming Corner RGB", img: "photo-1612287230202-1ff1d85d1bdf", cats: [2, 5, 1] },
    { titulo: "Home Office Elegante", img: "photo-1595846519845-68e298c2edd8", cats: [3, 0, 6] },
    { titulo: "Setup Ultrawide Imersivo", img: "photo-1547082299-de196ea013d6", cats: [1, 3, 5] },
    { titulo: "Estação de Trabalho Pro", img: "photo-1593642634367-d91a135587b5", cats: [3, 1, 0] },
    { titulo: "Setup Cozy com Plantas", img: "photo-1585412459212-9ca2cc89f52f", cats: [7, 4, 6] },
    { titulo: "Battlestation Competitivo", img: "photo-1598550476439-6847785fcea6", cats: [2, 5, 1] },
    { titulo: "Workspace Minimalista Zen", img: "photo-1600494603989-9650cf6ddd3d", cats: [0, 6, 3] },
    { titulo: "Setup Dual Monitor Pro", img: "photo-1587831990711-23ca6441447b", cats: [3, 1, 5] },
    { titulo: "Gaming Room Completo", img: "photo-1593640408182-31c70c8268f5", cats: [2, 5, 4] },
    { titulo: "Home Studio Musical", img: "photo-1598488035139-bdbb2231ce04", cats: [4, 5, 3] },
    { titulo: "Setup All Apple", img: "photo-1611532736597-de2d4265fba3", cats: [0, 1, 6] },
    { titulo: "Workspace Criativo Colorido", img: "photo-1618221195710-dd6b41faaea6", cats: [4, 6, 3] },
    { titulo: "Setup Produtividade Máxima", img: "photo-1593642632559-0c6d3fc62b89", cats: [3, 0, 1] },
    { titulo: "Corner Gaming Compacto", img: "photo-1542744173-8e7e53415bb0", cats: [2, 0, 5] },
    { titulo: "Escritório em Casa Luxo", img: "photo-1600585154526-990dced4db0d", cats: [4, 3, 6] },
    { titulo: "Setup Developer Escuro", img: "photo-1537498425277-c283d32ef9db", cats: [5, 3, 1] },
    { titulo: "Workspace com Vista", img: "photo-1606836591695-4d58a73eba1e", cats: [6, 0, 3] },
    { titulo: "Gaming Setup RGB Max", img: "photo-1600861194942-f883de0dfe96", cats: [2, 5, 4] },
    { titulo: "Setup Triple Monitor", img: "photo-1593640495253-23196b27a87f", cats: [3, 1, 2] },
    { titulo: "Home Office Aconchegante", img: "photo-1618221381711-42ca8ab6e908", cats: [7, 6, 3] },
    { titulo: "Estação Gamer Streamer", img: "photo-1603302576837-37561b2e2302", cats: [2, 4, 5] },
    { titulo: "Setup Clean Aesthetic", img: "photo-1600566753190-17f0baa2a6c3", cats: [0, 6, 1] },
    { titulo: "Workspace Industrial", img: "photo-1600607687939-ce8a6c25118c", cats: [4, 5, 7] },
    { titulo: "Setup Portátil Nômade", img: "photo-1600880292203-757bb62b4baf", cats: [0, 3, 1] },
    { titulo: "Gaming Den Épico", img: "photo-1605647540924-852290f6b0d5", cats: [2, 5, 4] },
    { titulo: "Escritório Executivo", img: "photo-1600585154084-4e5fe7c39198", cats: [3, 4, 6] },
    { titulo: "Setup Podcast Pro", img: "photo-1598550473359-433795503a0f", cats: [4, 5, 3] },
    { titulo: "Corner Desk Compacto", img: "photo-1600508774634-4e11d34730e2", cats: [0, 3, 1] },
    { titulo: "Setup Retro Moderno", img: "photo-1612287230202-1ff1d85d1bdf", cats: [4, 2, 1] },
    { titulo: "Workspace Natural Light", img: "photo-1600210492486-724fe5c67fb0", cats: [6, 0, 7] },
    { titulo: "Gaming Battlestation 2024", img: "photo-1593640408182-31c70c8268f5", cats: [2, 1, 5] },
    { titulo: "Setup Freelancer", img: "photo-1600494603989-9650cf6ddd3d", cats: [3, 0, 6] },
    { titulo: "Home Office Garden View", img: "photo-1600566752355-35792bedcfea", cats: [6, 7, 3] },
    { titulo: "Setup Editor de Vídeo", img: "photo-1593640495390-11b80004afe9", cats: [3, 4, 1] },
    { titulo: "Gaming Corner Aesthetic", img: "photo-1600861194942-f883de0dfe96", cats: [2, 4, 0] },
    { titulo: "Workspace Boho Chic", img: "photo-1600210491369-e753d80a41f3", cats: [4, 7, 6] },
    { titulo: "Setup Programador Senior", img: "photo-1537498425277-c283d32ef9db", cats: [3, 5, 1] },
    { titulo: "Home Office Feminino", img: "photo-1600585154526-990dced4db0d", cats: [4, 6, 0] },
    { titulo: "Setup Estudante Tech", img: "photo-1593642634367-d91a135587b5", cats: [0, 3, 1] },
    { titulo: "Gaming Room Dark Mode", img: "photo-1616588589676-62b3bd4ff6d2", cats: [2, 5, 4] },
    { titulo: "Escritório Criativo", img: "photo-1618221195710-dd6b41faaea6", cats: [4, 3, 6] },
    { titulo: "Setup Day Trader", img: "photo-1587831990711-23ca6441447b", cats: [3, 1, 5] },
    { titulo: "Workspace Artista Digital", img: "photo-1542744094-24638eff58bb", cats: [4, 6, 0] },
    { titulo: "Setup Cyberpunk Vibes", img: "photo-1612287230202-1ff1d85d1bdf", cats: [5, 2, 4] },
    { titulo: "Home Office Corporativo", img: "photo-1600585154340-be6161a56a0c", cats: [3, 1, 6] },
    { titulo: "Setup Minimalist Black", img: "photo-1555099962-4199c345e5dd", cats: [0, 5, 1] },
    { titulo: "Gaming Setup Console", img: "photo-1550745165-9bc0b252726f", cats: [2, 4, 5] },
    { titulo: "Workspace Designer UX", img: "photo-1547082299-de196ea013d6", cats: [4, 3, 0] },
  ];

  const autores = [
    "Gabriel Santos", "Mariana Costa", "Bruno Lima", "Carla Ribeiro", "Diego Martins",
    "Fernanda Oliveira", "Henrique Silva", "Isabela Souza", "João Pedro", "Larissa Mendes",
    "Mateus Alves", "Natália Ferreira", "Otávio Rocha", "Patrícia Campos", "Rafael Cardoso",
    "Sabrina Dias", "Thiago Nunes", "Vanessa Gomes", "William Santos", "Yasmin Barros"
  ];

  const fontes = ["Instagram", "Twitter", "Pinterest", "Reddit", "Behance", "Dribbble", null];

  return setupTemplates.map((template, index) => {
    const setupId = `setup-${11 + index}`;
    const autor = autores[index % autores.length];
    const fonte = fontes[index % fontes.length];
    const numProdutos = 3 + (index % 4);

    return {
      id: setupId,
      titulo: template.titulo,
      descricao: `Um setup incrível que combina estilo e funcionalidade para criar o ambiente perfeito de trabalho e lazer.`,
      imagemUrl: `https://images.unsplash.com/${template.img}?w=800&q=80`,
      imagens: [],
      videoUrl: null,
      isVideo: index % 7 === 0,
      autor,
      fonte,
      fonteUrl: fonte ? `https://${fonte.toLowerCase()}.com` : null,
      destaque: index % 5 === 0,
      visualizacoes: 300 + (index * 47) % 2000,
      createdAt: new Date(),
      updatedAt: new Date(),
      categorias: template.cats.map(catIndex => mockCategorias[catIndex]),
      produtos: Array.from({ length: numProdutos }, (_, prodIndex) => ({
        id: `prod-${setupId}-${prodIndex + 1}`,
        nome: ["Monitor 4K", "Teclado Mecânico", "Mouse Wireless", "Webcam HD", "Headset Pro", "Mesa Ajustável", "Cadeira Ergonômica"][prodIndex % 7],
        descricao: prodIndex === 0 ? "Produto destaque do setup" : null,
        categoria: ["Monitor", "Teclado", "Mouse", "Webcam", "Headphone", "Mesa", "Cadeira"][prodIndex % 7],
        imagemUrl: null,
        preco: [2499, 899, 599, 799, 1299, 1899, 2499][prodIndex % 7],
        moeda: "BRL",
        linkCompra: "https://amazon.com.br",
        loja: ["Amazon", "Kabum", "Pichau", "Terabyte"][prodIndex % 4],
        destaque: prodIndex === 0,
        ordem: prodIndex,
        setupId,
        createdAt: new Date(),
        updatedAt: new Date(),
      })),
    };
  });
}

// Funções para obter dados mock
export function getMockSetups(): SetupWithRelations[] {
  return mockSetups;
}

export function getMockSetupById(id: string): SetupWithRelations | null {
  return mockSetups.find((s) => s.id === id) || null;
}

export function getMockCategorias(): Categoria[] {
  return mockCategorias;
}

export function getMockCategoriaBySlug(slug: string) {
  const categoria = mockCategorias.find((c) => c.slug === slug);
  if (!categoria) return null;

  const setups = mockSetups.filter((s) =>
    s.categorias.some((c) => c.slug === slug)
  );

  return {
    ...categoria,
    setups,
  };
}
